config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :rooms, :furnitures, :houses
  resources :room_furnitures, only: [:new, :create, :edit, :update]

  get '/', to: "home#welcome", as: 'home'
  get '/profile', to: "home#profile", as: 'profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/furniture.rb
class Furniture < ApplicationRecord
    has_many :room_furnitures
    has_many :rooms, through: :room_furnitures
end

app/models/house.rb
class House < ApplicationRecord
    has_many :rooms

    def self.search(search)
        if search
            houses_hash = {}
            House.all.each {|house| houses_hash[house] = house.rooms.count }
            results_hash = houses_hash.select{|k,v| v == search.to_i}.keys
            !results_hash.empty? ? results_hash : House.all

        else
            House.all
        end
    end
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :house

    has_many :room_furnitures
    has_many :furnitures, through: :room_furnitures

    def self.search(search)
        if !search.blank?
            Room.all.where(primary_color_scheme: search)
        else
            Room.all
        end
    end

    def self.color_schemes_list
        Room.all.map {|room| room.primary_color_scheme}.uniq
    end
end

app/models/room_furniture.rb
class RoomFurniture < ApplicationRecord
    belongs_to :room
    belongs_to :furniture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/furniture_controller.rb
class FurnitureController < ApplicationController
  before_action :find_furniture, only: [:show, :edit]

  def show
  end

  def index
    @furnitures = Furniture.all
  end

  def new
    @furniture = Furniture.new
  end

  def edit
    @furniture.update(furniture_params)
    redirect_to furniture_path(@furniture)
  end

  private

  def furniture_params
    params.require(:furniture).permit(:style, :category, :img_url)
  end

  def find_furniture
    @furniture = Furniture.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def profile
    end

    def welcome
        @featured_room = Room.all.sample
    end

end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
    
    def index
        @houses = House.search(params[:search])
    end

    def show
        @house = House.find(params[:id])
    end

    private

    def house_params
        params.require(:house).permit(:search)        
    end
    
end

app/controllers/room_furnitures_controller.rb
class RoomFurnituresController < ApplicationController
  def new
    @room_furniture = RoomFurniture.new
  end

  def create
    @room_furniture = RoomFurniture.create(rf_params)
    redirect_to room_path(@room_furniture.room)
  end

  def edit
    @room_furniture = RoomFurniture.find(params[:id])
  end

  def update
    @rf = RoomFurniture.find(params[:id])
    @rf.update(rf_params)
    redirect_to room_path(@rf.room)
  end

  private

  def rf_params
    params.require(:room_furniture).permit(:room_id, :furniture_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  before_action :find_room, only: [:show, :edit, :update]

  def show
  end

  def index
    @select_array = Room.color_schemes_list
    @rooms = Room.search(params[:search])
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def update
    @room.update(room_params)
    redirect_to room_path(@room)
  end
  
  
  private

  def room_params
    params.require(:room).permit(:title, :style, :primary_color_scheme, :img_url, :blurb, :long_description, :search)
  end

  def find_room
    @room = Room.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/furniture_helper.rb
module FurnitureHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/room_furnitures_helper.rb
module RoomFurnituresHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/furniture/edit.html.erb
<h1>Edit furniture:</h1>

<%= form_for @furniture do |f| %>
<%= f.label :category, "Category" %>
<%= f.text_field :category %>
<%= f.label :style, "Style" %>
<%= f.text_field :style %>
<%= f.label :img_url, "Image URL" %>
<%= f.text_field :img_url %>
<%= f.submit %>
<% end %>

app/views/furniture/index.html.erb
<h1>All Furniture</h1>

<ul>
<% @furnitures.each do |furn| %>
<li><%= link_to  furn.category, furniture_path(furn) %></li>
</ul>

<% end %>

app/views/furniture/new.html.erb
<h1>Add a new piece of furniture:</h1>

<%= form_for @furniture do |f| %>
<%= f.label :category, "Category" %>
<%= f.text_field :category %>
<%= f.label :style, "Style" %>
<%= f.text_field :style %>
<%= f.label :img_url, "Image URL" %>
<%= f.text_field :img_url %>
<%= f.submit %>
<% end %>

app/views/furniture/show.html.erb
<h1><%= @furniture.style %> <%= @furniture.category %></h1>

This piece of furniture has been used in:
<ul>
<% @furniture.rooms.each do |room| %>
    <li><<%= link_to  room.title, room_path(room) %></li>
<% end %>

</ul>

app/views/home/profile.html.erb
<div class='profile'>
<h1 align="center">Who am I?</h1>

<img class='profile-img' src = "https://lh3.googleusercontent.com/c6YmCtO3Ik7ezR7gLi-QLJlbW6VM9MDNcobQpoSlDjCIH14GaOS8HBtNd0cjLHT_XEZOACJLZ_cgW_Myf-Z7DANm_-N-f12goxx7xywTzI-6e9gUlw31mZY-gvJZwqRvvMQ8ov6m2eDaw9FJwF-NbfBWeTyEhn9yAVueNVZjIYVB0dUlb73x3e0W30ZpOIw7Vy1hHiirEo-uglzvW-eos2ZuNqUY-lcmhncW5BQT6DVrKEn-eiYOczPABbddXJtXS-18SNrlGeZXAUfPFfccG_roJghtjMiY0a054vDFkYMGqm4t9--iNquwWL0ZsQQfN_162rhmdkpgO13Q4o7Tp-_xMR49RVCY0_Aeigbu6h7zkHty97DXHaBNF7Ecs5UpJf_pXCQllEUQ1psiDzUUVNY2zvZksJjXl3Xk2i4Xf92-M5Y6seJC3wChVwRv2iW1A4PvSKzmCMb6s9r3NyE0tGnNTu4B_NOC5jt5H9A8jnK0MJJp8Tsezw55dW7-m3E-PZTsmGQZARqK15vSDkOIfokSGgH8iU2d2O66zsomcC4IhtvWmHkA5n1BFRACs-I4f1-XR-ADA9sbca6DGfeFygI-mYPHPYPx7T7rgG-hEmY39CzCgpUTOU4QQuxIInWqyeW9HkrRiSNe7kLJklVbfSoE-fd6g5CnmKgvTqBinCrD1zMtdHM4S5UXyAq7nQ=w1100-h1466-no?authuser=0">

    <div class='profile-text'>
    <p>My name is Srishti, and I'm currently a student at Flatiron School.
    I began my coding journey many moons ago with learning HTML and CSS to customize my Neopets' profile pages...
    The journey has been crazy fun, and for this first blog post I'm highlighting all the fun things I've gotten to do in my free time! </p>

    <ul> <b>Other fun facts about me: </b>
    <li>I spent half my time in college studying biochemistry and the other half studying economics.</li>
    <li>I've been to either 33 or 34 countries in the world</li>
    <li>I live in Brooklyn, NY (although is it really living if I'm forced to be here by a so-called global pandemic?)</li>
    <li>I've spent the majority of my adult life in Finance and Consulting</li>
    <li>I've watched every episode of The Office and Parks and Rec, and could recite some episodes from memory</li>
    </ul>

    That's all I got!
    </div>
</div>

app/views/home/welcome.html.erb
<div class='home-container'>
<h1>Welcome to my Sims 4 House Build Portfolio!</h1>

<p>I started on my Sims journey a few months ago, as quarantine set in, along with boredom and the insanity that comes with it.
I very quickly became enamored, not with game play, but the endless opportunities for interior design that it provided.</p>

<p>For full disclosure, I don't have all of the expansion packs that Sims comes with; so far I've only got the base game, and Jungle Adventure and literally just bought the Get Together, Laundry Stuff and Spa Day packs. 
I think my favorite is Jungle Adventure for all of the gorgeous colors it contains; I'm a sucker for yellow walls, and the antique-y blue it's rife with.  
Since quarantine has locked me down, Sims has been amazing in allowing my imagination to wander the universe. I'm very excited about the houses I've gotten to build in the process, and very excited to share them with you!
Feel free to peruse this website for the houses, rooms, and furniture I've used in my journey on Sims. </p>
</div>
<br>
<hr size="1" color="grey" width="30%" align="center">

<div class='featured-room'>
    <%# <h3 align="center">Featured Room: <%= @featured_room.category %> from <%= @featured_room.house.name %></h3> %>

    <div class='featured-container'>
        <%# <a href="<%= room_path(@featured_room) %>">  %>
        <%# <img class='featured-img' src="<%= @featured_room.img_url %>" align="center"> %>
        <div class='overlay'>
        <%# <div class='centered'><%= @featured_room.blurb %></div> %>
        </div>
        </a>
    </div>
</div>

app/views/houses/index.html.erb
<h1 align="center">Houses I've Built</h1>

<div class='header nav'>

<h3 align="right">Search by number of rooms: 
<%= form_tag(houses_path, method: :get) do %>
  <%= number_field_tag(:search, params[:search]) %>
  <%= submit_tag ("Search") %>
<% end %>
</h3>
</div>

<p></p>
<div class="index_container">
  <% @houses.each do |house| %>
    <div class="index_tile">
    <img class="index_img" src="<%= house.img_url %>" alt="<%= house.name%>">

    <p><%= link_to house.name, house_path(house) %></p>
    </div>
  <% end %>
</div>

app/views/houses/show.html.erb
<h1 align="center">Welcome to <%= @house.name %>!</h1>


<div class='show-container'>
  <div class='show-pics'>
    <img class="show-img" src="<%= @house.img_url %>" alt="<%= @house.name%>" style="height:800px" align="center">
  <marquee behavior="scroll" direction="left">
    <img class="show-img" src="<%= @house.img_url2 %>" alt="<%= @house.name%>" style="height:400px">
    <img class="show-img" src="<%= @house.img_url3 %>" alt="<%= @house.name%>" style="height:400px">
    <img class="show-img" src="<%= @house.img_url4 %>" alt="<%= @house.name%>" style="height:400px">
  </marquee>
  </div>
  
  <p>Description: </p>
  <p><%= @house.description %></p> 

    <ul>
    <% @house.rooms.each do |room| %>
    <li><%= link_to  room.category, room_path(room) %> | <%= room.title %></li>
    <% end %>
    </ul>

</div>

<br>
<%= link_to  "All Houses", houses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimsSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class='header'>
    <div class='header title'>Srishti's Sims Portfolio </div>
    <div class='header nav'>
      <p><%= link_to  "Welcome", home_path %> | <%= link_to  "All Houses", houses_path %> | <%= link_to  "All Rooms", rooms_path %> | <%= link_to  "Profile", profile_path %></div></p>
      <br>
    </div>
  </div>
    <%= yield %>

  <footer>
  <div class='body footer'>
  <p> <%= link_to  "LinkedIn", 'https://www.linkedin.com/in/srishti-nath-0346ab8a/' %> | <%= link_to  "E-mail", 'mailto:srishti.nath@gmail.com' %> </p>
  </div>
  </footer>
  </body>
</html>

app/views/room_furnitures/edit.html.erb
<h1>Edit an existing record:</h1>

<%= form_for @room_furniture do |f| %>
<p><%= f.label :room_id, "Room" %></p>
<%= f.collection_select(:room_id, Room.all, :id, :title) %>
<p><%= f.label :furniture_id, "Furniture" %></p>
<%= f.collection_select(:furniture_id, Furniture.all, :id, :category) %>
<p><%= f.submit %></p>
<% end %>

app/views/room_furnitures/new.html.erb
<h1>Add a new record:</h1>

<%= form_for @room_furniture do |f| %>
<p><%= f.label :room_id, "Room" %></p>
<%= f.collection_select(:room_id, Room.all, :id, :title) %>
<p><%= f.label :furniture_id, "Furniture" %></p>
<%= f.collection_select(:furniture_id, Furniture.all, :id, :category) %>
<p><%= f.submit %></p>
<% end %>

app/views/rooms/edit.html.erb
<h1>Edit a room</h1>

<center><img class="show-img" src="<%= @room.img_url %>" alt="<%= @room.title%>" style="width:60%"></center>

<%= form_for @room do |f| %>
<p><%= f.label :category, "Category (Kitchen, Bathroom, etc.)" %></p>
<%= f.text_field :category %>

<p><%= f.label :primary_color_scheme, "Color Scheme" %></p>
<%= f.text_field :primary_color_scheme %>

<p><%= f.label :style, "Style" %></p>
<%= f.text_field :style %>

<p><%= f.label :title, "Title" %></p>
<%= f.text_field :title %>

<p><%= f.label :img_url, "Image URL" %></p>
<%= f.text_field :img_url %>

<p><%= f.label :blurb, "Blurb" %></p>
<%= f.text_area :blurb %>

<p><%= f.label :long_description, "Description" %></p>
<%= f.text_area :long_description %>

<p><%= f.submit %></p>
<% end %>

<br>

app/views/rooms/index.html.erb
<h1 align="center">Rooms</h1>

<div class='header nav'>

<h3 align="right">Search by color scheme:

<%= form_tag(rooms_path, method: :get) do %>
  <%= select_tag(:search, options_for_select(@select_array), include_blank: true) %>
  <%= submit_tag ("Search") %>
<% end %>
</h3>
</div>

<div class="index_container">
  <% @rooms.each do |room| %>
      <div class="index_tile">
        <a href = "<%= room_path(room) %>">
        <img class="index_img" src="<%= room.img_url %>" alt="<%= room.title%>">
        <p><%= room.title %></p>
        </a>
        <p><%= room.blurb %></p>
      </div>
  <% end %>
</div>  

app/views/rooms/new.html.erb
<h1>Add a room</h1>

<%= form_for @room do |f| %>
<p><%= f.label :category, "Category (Kitchen, Bathroom, etc.)" %></p>
<%= f.text_field :category %>

<p><%= f.label :primary_color_scheme, "Color Scheme" %></p>
<%= f.text_field :primary_color_scheme %>

<p><%= f.label :style, "Style" %></p>
<%= f.text_field :style %>

<p><%= f.label :title, "Title" %></p>
<%= f.text_field :title %>

<p><%= f.label :img_url, "Image URL" %></p>
<%= f.text_field :img_url %>

<p><%= f.label :blurb, "Blurb" %></p>
<%= f.text_area :blurb %>

<p><%= f.label :long_description, "Description" %></p>
<%= f.text_area :long_description %>

<p><%= f.label :house, "House" %></p>
<%= f.collection_select(:house, House.all, :id, :name) %>

<%= f.submit %>
<% end %>

app/views/rooms/show.html.erb
<h1 align="center"><%= @room.title.titleize  %></h1>

<p align="center" style="color:grey"><%= @room.blurb %></p>

<div class='show-container'>
    <img class="show-img" src="<%= @room.img_url %>" alt="<%= @room.title%>">
  <p></p>
  <p align="center">Category: <%= @room.category %> |  Style: <%= @room.style %></p>

  <p><%= @room.long_description %></p>
 
</div>

<br>
<p align="right">Go back to <%= link_to  @room.house.name, house_path(@room.house) %></p>
<p align="right"><%= link_to  "All Rooms", rooms_path %></p>